services:
  db:
    image: postgres:16
    container_name: app_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-SmartPocketDB}
      POSTGRES_USER: ${POSTGRES_USER:-SmartPocket}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./SmartPocketAPI
      dockerfile: Dockerfile
    container_name: app_api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: http://+:8080
      Configuration__ConnectionString: "Host=db;Port=5432;Database=${POSTGRES_DB:-SmartPocketDB};Username=${POSTGRES_USER:-SmartPocket};Password=${POSTGRES_PASSWORD:-12345678};Pooling=true"
      Configuration__CommandTimeOut: "30"
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health" ]
      interval: 15s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./SmartPocketWeb2
      dockerfile: Dockerfile
    container_name: app_web
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  pgdata:
