// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPocketAPI.Database;

#nullable disable

namespace SmartPocketAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250206065656_userupdate")]
    partial class userupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("SmartPocketAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionSpanish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSpanish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            DescriptionSpanish = "",
                            Name = "Food",
                            NameSpanish = "Comida",
                            UserId = new Guid("95eb5d5b-dd03-4c31-8a59-80d59b73df7c")
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            DescriptionSpanish = "",
                            Name = "Gas",
                            NameSpanish = "Gasolina",
                            UserId = new Guid("95eb5d5b-dd03-4c31-8a59-80d59b73df7c")
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            DescriptionSpanish = "",
                            Name = "Hobbies",
                            NameSpanish = "Hobbies",
                            UserId = new Guid("95eb5d5b-dd03-4c31-8a59-80d59b73df7c")
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            DescriptionSpanish = "",
                            Name = "Shopping",
                            NameSpanish = "Compras",
                            UserId = new Guid("95eb5d5b-dd03-4c31-8a59-80d59b73df7c")
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            DescriptionSpanish = "",
                            Name = "Bank",
                            NameSpanish = "Bancarios",
                            UserId = new Guid("95eb5d5b-dd03-4c31-8a59-80d59b73df7c")
                        });
                });

            modelBuilder.Entity("SmartPocketAPI.Models.Frequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSpanish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Frequency", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Daily",
                            NameSpanish = "Diario"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Weekly",
                            NameSpanish = "Semanal"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Monthly",
                            NameSpanish = "Mensual"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bimonthly",
                            NameSpanish = "Bimestral"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Quarter",
                            NameSpanish = "Trimestral"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Anual",
                            NameSpanish = "Anual"
                        });
                });

            modelBuilder.Entity("SmartPocketAPI.Models.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditCardPaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovementTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecurringPaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriId");

                    b.HasIndex("CreditCardPaymentId");

                    b.HasIndex("MovementTypeId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("RecurringPaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("Movement", (string)null);
                });

            modelBuilder.Entity("SmartPocketAPI.Models.MovementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSpanish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MovementType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Paymenty",
                            NameSpanish = "Pago"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Income",
                            NameSpanish = "Ingreso"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Purchase",
                            NameSpanish = "Compra"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CreditCard Payment",
                            NameSpanish = "Pago a Tarjeta de Credito"
                        });
                });

            modelBuilder.Entity("SmartPocketAPI.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultInterestRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCreditCard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethodTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethod", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bank = "",
                            DefaultInterestRate = 0m,
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCreditCard = false,
                            Name = "Cash",
                            PaymentMethodTypeId = 1,
                            TransactionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("95eb5d5b-dd03-4c31-8a59-80d59b73df7c")
                        });
                });

            modelBuilder.Entity("SmartPocketAPI.Models.PaymentMethodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSpanish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethodType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cash",
                            NameSpanish = "Efectivo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Credit Card",
                            NameSpanish = "Tarjeta de Credito"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Debit Card",
                            NameSpanish = "Tarjeta de Debito"
                        });
                });

            modelBuilder.Entity("SmartPocketAPI.Models.RecurringPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FrecuencyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InstallmentAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInterestFreePayment")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FrecuencyId");

                    b.HasIndex("UserId");

                    b.ToTable("RecurringPayments");
                });

            modelBuilder.Entity("SmartPocketAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("95eb5d5b-dd03-4c31-8a59-80d59b73df7c"),
                            Email = "admin@admin.com",
                            Name = "Admin",
                            Password = "5IrYpxI+Y3DE8f6ZP6y1qw==:dR01XFPGqVy+ZUb/7gsPLGX7NkpY0dcgzPjgyUT22r8="
                        });
                });

            modelBuilder.Entity("SmartPocketAPI.Models.Category", b =>
                {
                    b.HasOne("SmartPocketAPI.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartPocketAPI.Models.Movement", b =>
                {
                    b.HasOne("SmartPocketAPI.Models.Category", "Category")
                        .WithMany("Movements")
                        .HasForeignKey("CategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPocketAPI.Models.PaymentMethod", "CreditCardPayment")
                        .WithMany("Payments")
                        .HasForeignKey("CreditCardPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPocketAPI.Models.MovementType", "MovementType")
                        .WithMany()
                        .HasForeignKey("MovementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPocketAPI.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Movements")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPocketAPI.Models.RecurringPayment", "RecurringPayment")
                        .WithMany("Movements")
                        .HasForeignKey("RecurringPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPocketAPI.Models.User", "User")
                        .WithMany("Movements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreditCardPayment");

                    b.Navigation("MovementType");

                    b.Navigation("PaymentMethod");

                    b.Navigation("RecurringPayment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartPocketAPI.Models.PaymentMethod", b =>
                {
                    b.HasOne("SmartPocketAPI.Models.PaymentMethodType", "PaymentMethodType")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("PaymentMethodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPocketAPI.Models.User", "User")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethodType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartPocketAPI.Models.RecurringPayment", b =>
                {
                    b.HasOne("SmartPocketAPI.Models.Frequency", "Frequency")
                        .WithMany("RecurringPayments")
                        .HasForeignKey("FrecuencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPocketAPI.Models.User", "User")
                        .WithMany("RecurringPayments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frequency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartPocketAPI.Models.Category", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("SmartPocketAPI.Models.Frequency", b =>
                {
                    b.Navigation("RecurringPayments");
                });

            modelBuilder.Entity("SmartPocketAPI.Models.PaymentMethod", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SmartPocketAPI.Models.PaymentMethodType", b =>
                {
                    b.Navigation("PaymentMethods");
                });

            modelBuilder.Entity("SmartPocketAPI.Models.RecurringPayment", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("SmartPocketAPI.Models.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Movements");

                    b.Navigation("PaymentMethods");

                    b.Navigation("RecurringPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
